### ISSUE TITLE
[M4] Test coverages staged ledger diff

### ISSUE THREAD

**Issue by polarbeargo** [ChainSafe/mina-rs#143]
**Task summary**

_Originally posted by @jspada in https://github.com/ChainSafe/mina-rs/pull/94#discussion_r764134519_
- [x] test: StagedLedgerPreDiffOne
- [x] test: Implement test_coin_base_fee_transfer().
- [x] test: Implement test_coin_base_balance_data(). 
- [x] test: Implement test_fee_transfer_balance_data().
- [ ] test: Implement test_snapp_command().

**Specification reference**

- MinaProtocol [staged_ledger_diff.ml](https://github.com/MinaProtocol/mina/blob/af76cb7980d5e81e704120290a850ea9c6f8522e/src/lib/staged_ledger_diff/staged_ledger_diff.mli)
- MinaProtocol [staged_ledger_diff.mli](https://github.com/MinaProtocol/mina/blob/af76cb7980d5e81e704120290a850ea9c6f8522e/src/lib/staged_ledger_diff/staged_ledger_diff.ml)

**Comment by polarbeargo** [comment]
Currently, put this into an icebox wait O1 lab response.
