### ISSUE TITLE
M2 - implement consensus checkpointing algorithms

### ISSUE THREAD

**Issue by noot** [ChainSafe/mina-rs#24]
**Task summary**

During chain/block selection, checkpointing is an important step in mina consensus that helps in figuring out if a fork is a long range or a short range.

- implement `initCheckpoints`, `updateCheckpoints`, and `isShortRange` algorithms outlined here: https://github.com/MinaProtocol/mina/blob/32f529d8d8d712a44ee75be66061ce08cbdc8924/docs/specs/consensus/README.md#53-decentralized-checkpointing
- requires `consensus_state` type to be defined

**Comment by polarbeargo** [comment]
To avoid  x86_64 & wasm CI error, the function name should be `init_checkpoints`, `update_checkpoints` and `is_short_range`. Just a reminder to myself.

**Comment by polarbeargo** [comment]
**Summary of changes**
Changes introduced in this pull request:
- 
Base on the branch [noot/checkpoint](https://github.com/ChainSafe/mina-rs/commits/noot/checkpoint) continue with issue #24 

- [x] Add `initCheckpoints`, and `isShortRange` algorithms outlined here: https://github.com/MinaProtocol/mina/blob/32f529d8d8d712a44ee75be66061ce08cbdc8924/docs/specs/consensus/README.md#53-decentralized-checkpointing
- [x] Add defined `consensus_state` type.
- [x] Add license in `checkpoint.rs`.
- [x] Update library.
- [x] Fix: Use of moved value.
- [x] Test: Implement Implement wasm-bindgen-test in consensus directly for issue #72 .
- [x] Feat: Implement `is_short_range()` for short-range fork check, `test_init_checkpoints` and , `init_checkpoints` for  genesis checkpoints follow new spec.  

Cargo build & wasm-pack test --node passed.
**Specification reference**

- 
https://github.com/MinaProtocol/mina/blob/32f529d8d8d712a44ee75be66061ce08cbdc8924/docs/specs/consensus/README.md

**Other information and links**

https://github.com/MinaProtocol/mina/blob/develop/src/lib/consensus/proof_of_stake.ml
