### ISSUE TITLE
Create Merkle Address and Range traits

### ISSUE THREAD

**Issue by mmacedoeu** [ChainSafe/mina-rs#39]
**Task summary**

WIP task, this should change, obs.:check if all functions are required

Create trait for some functions related with Direction on Merkle tree forming an Address also Range trait

Address Trait:
- [x] of_byte_string(&self, str: &str) -> Self::T;
- [x] of_directions(&self, directions: &[Direction]) -> Self::T;
- [x] root(&self) -> Self::T;
- [x] slice(&self, start: usize, end: usize) -> Self::T;
- [x] get(&self, pos: usize) -> Self::T;
- [x] copy(other: &Self::T) -> Self::T;
- [x] parent(&self) -> anyhow::Result<Self::T>;
- [x] child(&self, ledger_depth: usize, direction: Direction) -> anyhow::Result<Self::T>;
- [x] child_exn(&self, ledger_depth: usize, direction: Direction) -> Self::T;
- [x] parent_exn(&self) -> Self::T;
- [x] dirs_from_root(&self, other: Self::T) -> Vec<Direction>;
- [x] sibling(&self, other: Self::T) -> Self::T;
- [x] next(&self) -> Option<Self::T>;
- [x] prev(&self) -> Option<Self::T>;
- [x] is_leaf(&self, ledger_depth: usize, other: Self::T) -> bool;
- [x] is_parent_of(&self, maybe_child: Self::T) -> bool;
- [x] serialize(&self, ledger_depth: usize) -> Vec<u8>;
- [x] to_string(&self) -> String;
- [x] depth(&self) -> Self::T;
- [x] height(&self, ledger_depth:usize) -> usize;
- [x] to_int(&self) -> usize;
- [x] of_int_exn(&self, ledger_depth: usize, other: usize) -> Self::T;

Create Range trait for functions:
- [x] subtree_range(&self, ledger_depth: usize);
- [x] subtree_range_seq(&self, ledger_depth: usize) -> Self::T;

**Specification reference**

- 
https://github.com/MinaProtocol/mina/blob/develop/docs/specs/merkle_tree.md

**Other information and links**

https://github.com/MinaProtocol/mina/blob/develop/src/lib/merkle_address/merkle_address.mli
