### ISSUE TITLE
Create Merkle-ledger related Traits

### ISSUE THREAD

**Issue by mmacedoeu** [ChainSafe/mina-rs#40]
**Task summary**

WIP task, this should change, obs.:check if all functions are required
Create Traits related with Merkle tree/ledger

- [x] Create trait for Merkle Location S with following functions:

    fn is_generic(&self) -> bool;
    fn is_account(&self) -> bool;
    fn is_hash(&self) -> bool;
    fn height(ledger_depth: usize, other: T) -> usize;
    fn root_hash(&self) -> T;
    fn last_direction(addr: &Addr::stable::v1::MerkleAddress) -> direction::Direction;
    fn to_path_exn(&self) -> Addr::stable::v1::MerkleAddress;
    fn parent(other: T) -> T;
    fn next(other: T) -> T;
    fn prev(other: T) -> T;
    fn sibling(other: T) -> T;

- [x] Create trait for Account with following functions:

    fn token(other: &Self::T) -> Self::TokenId;
    fn identifier(other: &Self::T) -> Self::AccountId;
    fn balance(other: &Self::T) -> Self::Balance;
    fn token_owner(other: &Self::T) -> bool;
    fn empty() -> Self::T;
    
- [x] Create trait for AccountID;
- [x] Create trait for Hash;
- [x] Create trait for Database;
- [x] Create trait for BaseLedger;
- [x] Create trait for Syncable;
- [x] Create trait for Key;
- [x] Create trait for Path;

**Specification reference**

- 
https://github.com/MinaProtocol/mina/blob/develop/docs/specs/merkle_tree.md

**Other information and links**

https://github.com/MinaProtocol/mina/blob/develop/src/lib/merkle_ledger/base_ledger_intf.ml
https://github.com/MinaProtocol/mina/blob/develop/src/lib/merkle_ledger/database_intf.ml
https://github.com/MinaProtocol/mina/blob/develop/src/lib/merkle_ledger/intf.ml
https://github.com/MinaProtocol/mina/blob/develop/src/lib/merkle_ledger/merkle_path_intf.ml
https://github.com/MinaProtocol/mina/blob/develop/src/lib/merkle_ledger/syncable_intf.ml
https://github.com/MinaProtocol/mina/blob/develop/src/lib/merkle_ledger/location_intf.ml
