### ISSUE TITLE
Implement functions from Merkle Address and Range traits on a concrete type

### ISSUE THREAD

**Issue by mmacedoeu** [ChainSafe/mina-rs#44]
**Task summary**

- [ ] of_byte_string
- [ ] of_directions
- [ ] root
- [ ] slice
- [ ] get
- [ ] copy
- [ ] parent
- [ ] child
- [ ] child_exn
- [ ] parent_exn
- [ ] dirs_from_root
- [ ] sibling
- [ ] next
- [ ] prev
- [ ] is_leaf
- [ ] is_parent_of
- [ ] serialize
- [ ] to_string
- [ ] fold
- [ ] subtree_range
- [ ] subtree_range_seq
- [ ] depth
- [ ] height
- [ ] to_int
- [ ] of_int_exn

**Specification reference**

- 

**Other information and links**

https://github.com/MinaProtocol/mina/blob/develop/src/lib/merkle_address/merkle_address.ml
