### ISSUE TITLE
Create Stage Ledger traits

### ISSUE THREAD

**Issue by mmacedoeu** [ChainSafe/mina-rs#49]
**Task summary**

Staged Ledger updates the current ledger with new transactions

WIP task, this should change, obs.:check if all functions are required

Create traits for Stage Ledger (deps for mina_transition) and it's dependencies traits:

Trait Scan_state:
- [ ]  val hash : t -> Staged_ledger_hash.Aux_hash.t
- [ ] val empty : constraint_constants:Genesis_constants.Constraint_constants.t -> unit -> t
- [ ] val snark_job_list_json : t -> string
- [ ] val staged_transactions : t -> Transaction.t With_status.t list
- [ ] val staged_transactions_with_protocol_states : t -> get_state:(State_hash.t -> Mina_state.Protocol_state.value Or_error.t)     -> (Transaction.t With_status.t * Mina_state.Protocol_state.value) list Or_error.t
- [ ] val all_work_statements_exn : t -> Transaction_snark_work.Statement.t list
- [ ] val required_state_hashes : t -> State_hash.Set.t
- [ ] val check_required_protocol_states : t -> protocol_states:Mina_state.Protocol_state.value list -> (State_hash.t * Mina_state.Protocol_state.value) list Or_error.t

Trait StagedLedger:
- [ ] val ledger : t -> Ledger.t
- [ ] val scan_state : t -> Scan_state.t
- [ ] val pending_coinbase_collection : t -> Pending_coinbase.t
- [ ] val create_exn : constraint_constants:Genesis_constants.Constraint_constants.t   -> ledger:Ledger.t   -> t
- [ ] val of_scan_state_and_ledger : logger:Logger.t   -> constraint_constants:Genesis_constants.Constraint_constants.t
  -> verifier:Verifier.t   -> snarked_ledger_hash:Frozen_ledger_hash.t   -> snarked_next_available_token:Token_id.t
  -> ledger:Ledger.t   -> scan_state:Scan_state.t   -> pending_coinbase_collection:Pending_coinbase.t   -> t Or_error.t Deferred.t
- [ ] val of_scan_state_and_ledger_unchecked : constraint_constants:Genesis_constants.Constraint_constants.t   -> narked_ledger_hash:Frozen_ledger_hash.t   -> snarked_next_available_token:Token_id.t   -> ledger:Ledger.t   -> scan_state:Scan_state.t   -> pending_coinbase_collection:Pending_coinbase.t   -> t Or_error.t Deferred.t
- [ ] val replace_ledger_exn : t -> Ledger.t -> t
- [ ] val proof_txns_with_state_hashes : t -> (Transaction.t With_status.t * State_hash.t) Non_empty_list.t option
- [x] val copy : t -> t
- [x] val hash : t -> Staged_ledger_hash.t
- [x] val apply :  ?skip_verification:[ `Proofs | `All ]   -> constraint_constants:Genesis_constants.Constraint_constants.t   -> t
  -> Staged_ledger_diff.t   -> logger:Logger.t   -> verifier:Verifier.t   -> current_state_view:Snapp_predicate.Protocol_state.View.t   -> state_and_body_hash:State_hash.t * State_body_hash.t
  -> coinbase_receiver:Public_key.Compressed.t   -> supercharge_coinbase:bool   -> ( [ `Hash_after_applying of Staged_ledger_hash.t ]
       * [ `Ledger_proof of
           (Ledger_proof.t * (Transaction.t With_status.t * State_hash.t) list)
           option ]
       * [ `Staged_ledger of t ]
       * [ `Pending_coinbase_update of bool * Pending_coinbase.Update.t ]
     , Staged_ledger_error.t )
     Deferred.Result.t
- [ ] val apply_diff_unchecked :
     constraint_constants:Genesis_constants.Constraint_constants.t
  -> t
  -> Staged_ledger_diff.With_valid_signatures_and_proofs.t
  -> logger:Logger.t
  -> current_state_view:Snapp_predicate.Protocol_state.View.t
  -> state_and_body_hash:State_hash.t * State_body_hash.t
  -> coinbase_receiver:Public_key.Compressed.t
  -> supercharge_coinbase:bool
  -> ( [ `Hash_after_applying of Staged_ledger_hash.t ]
       * [ `Ledger_proof of
           (Ledger_proof.t * (Transaction.t With_status.t * State_hash.t) list)
           option ]
       * [ `Staged_ledger of t ]
       * [ `Pending_coinbase_update of bool * Pending_coinbase.Update.t ]
     , Staged_ledger_error.t )
     Deferred.Result.t
- [x] val current_ledger_proof : t -> Ledger_proof.t option
- [ ] val create_diff :
     constraint_constants:Genesis_constants.Constraint_constants.t
  -> ?log_block_creation:bool
  -> t
  -> coinbase_receiver:Public_key.Compressed.t
  -> logger:Logger.t
  -> current_state_view:Snapp_predicate.Protocol_state.View.t
  -> transactions_by_fee:User_command.Valid.t Sequence.t
  -> get_completed_work:
       (   Transaction_snark_work.Statement.t
        -> Transaction_snark_work.Checked.t option)
  -> supercharge_coinbase:bool
  -> ( Staged_ledger_diff.With_valid_signatures_and_proofs.t
     , Pre_diff_info.Error.t )
     Result.t
- [ ] val can_apply_supercharged_coinbase_exn :
     winner:Public_key.Compressed.t
  -> epoch_ledger:Mina_base.Sparse_ledger.t
  -> global_slot:Mina_numbers.Global_slot.t
  -> bool
- [ ] val statement_exn :
     constraint_constants:Genesis_constants.Constraint_constants.t
  -> t
  -> [ `Non_empty of Transaction_snark.Statement.t | `Empty ] Deferred.t
- [ ] val of_scan_state_pending_coinbases_and_snarked_ledger :
     logger:Logger.t
  -> constraint_constants:Genesis_constants.Constraint_constants.t
  -> verifier:Verifier.t
  -> scan_state:Scan_state.t
  -> snarked_ledger:Ledger.t
  -> expected_merkle_root:Ledger_hash.t
  -> pending_coinbases:Pending_coinbase.t
  -> get_state:(State_hash.t -> Mina_state.Protocol_state.value Or_error.t)
  -> t Or_error.t Deferred.t
- [ ] val all_work_pairs :
     t
  -> get_state:(State_hash.t -> Mina_state.Protocol_state.value Or_error.t)
  -> ( Transaction.t
     , Transaction_witness.t
     , Ledger_proof.t )
     Snark_work_lib.Work.Single.Spec.t
     One_or_two.t
     list
     Or_error.t
- [ ] val all_work_statements_exn : t -> Transaction_snark_work.Statement.t list
- [ ] val check_commands :
     Ledger.t
  -> verifier:Verifier.t
  -> User_command.t list
  -> (User_command.Valid.t list, Verifier.Failure.t) Result.t
     Deferred.Or_error.t

Dependencies traits:
Candidates - staged_ledger_diff, transaction_snark_work, transaction_snark_scan_state, transaction_snark, ledger_proof
- [ ] Create deps traits

**Specification reference**

- 

**Other information and links**

https://github.com/MinaProtocol/mina/blob/develop/src/lib/staged_ledger/staged_ledger.mli
