### ISSUE TITLE
Create Frontier Base Traits

### ISSUE THREAD

**Issue by mmacedoeu** [ChainSafe/mina-rs#50]
**Task summary**

WIP task, need to check if all those are required

Trait Historical:
- [ ] val transition : t -> External_transition.Validated.t
- [ ] val scan_state : t -> Staged_ledger.Scan_state.t
- [ ] val pending_coinbase : t -> Pending_coinbase.t
- [ ] val staged_ledger_target_ledger_hash : t -> Ledger_hash.t
- [ ] val of_breadcrumb : Breadcrumb.t -> t

Trait Limited:
- [ ] val transition : t -> External_transition.Validated.t
- [ ] val hash : t -> State_hash.t
- [ ] val scan_state : t -> Staged_ledger.Scan_state.t
- [ ] val pending_coinbase : t -> Pending_coinbase.t
- [ ] val protocol_states :     t -> (State_hash.t * Mina_state.Protocol_state.value) list
- [ ] val create :
       transition:External_transition.Validated.t
    -> scan_state:Staged_ledger.Scan_state.t
    -> pending_coinbase:Pending_coinbase.t
    -> protocol_states:(State_hash.t * Mina_state.Protocol_state.value) list
    -> t

Trait Minimal:
- [ ] val hash : t -> State_hash.t
- [ ] val scan_state : t -> Staged_ledger.Scan_state.t
- [ ] val pending_coinbase : t -> Pending_coinbase.t
- [ ] val of_limited : Limited.t -> t
- [ ] val upgrade :
       t
    -> transition:External_transition.Validated.t
    -> protocol_states:( Mina_base.State_hash.t
                       * Mina_state.Protocol_state.Value.t )
                       list
    -> Limited.t
- [ ]   val create :
       hash:State_hash.t
    -> scan_state:Staged_ledger.Scan_state.t
    -> pending_coinbase:Pending_coinbase.t
    -> t

Trait RootData:
- [ ] val minimize : t -> Minimal.t
- [ ] val limit : t -> Limited.t

Trait BreadCumb:
- [ ] val create :
     validated_transition:External_transition.Validated.t
  -> staged_ledger:Staged_ledger.t
  -> just_emitted_a_proof:bool
  -> transition_receipt_time:Time.t option
  -> t
- [ ] val build :
     ?skip_staged_ledger_verification:[`All | `Proofs]
  -> logger:Logger.t
  -> precomputed_values:Precomputed_values.t
  -> verifier:Verifier.t
  -> trust_system:Trust_system.t
  -> parent:t
  -> transition:External_transition.Almost_validated.t
  -> sender:Envelope.Sender.t option
  -> transition_receipt_time:Time.t option
  -> unit
  -> ( t
     , [> `Invalid_staged_ledger_diff of Error.t
       | `Invalid_staged_ledger_hash of Error.t
       | `Fatal_error of exn ] )
     Result.t
     Deferred.t
- [ ] val validated_transition : t -> External_transition.Validated.t
- [ ] val staged_ledger : t -> Staged_ledger.t
- [ ] val just_emitted_a_proof : t -> bool
- [ ] val transition_receipt_time : t -> Time.t option
- [ ] val hash : t -> int
- [ ] val blockchain_state : t -> Mina_state.Blockchain_state.Value.t
- [ ] val protocol_state : t -> Mina_state.Protocol_state.Value.t
- [ ] val consensus_state : t -> Consensus.Data.Consensus_state.Value.t
- [ ] val consensus_state_with_hash :  t -> (Consensus.Data.Consensus_state.Value.t, State_hash.t) With_hash.t
- [ ] val blockchain_length : t -> Unsigned.UInt32.t
- [ ] val state_hash : t -> State_hash.t
- [ ] val parent_hash : t -> State_hash.t
- [ ] val block_producer : t -> Signature_lib.Public_key.Compressed.t
- [ ] val commands : t -> User_command.Valid.t With_status.t list
- [ ] val payments : t -> Signed_command.t With_status.t list
- [ ] val completed_works : t -> Transaction_snark_work.t list
- [ ] val mask : t -> Ledger.Mask.Attached.t
- [ ] val all_user_commands : t list -> Signed_command.Set.t
- [ ] val display : t -> display
- [ ] val name : t -> string

Trait Frontier::S : 
- [ ] val find_exn : t -> State_hash.t -> Breadcrumb.t
- [ ] val max_length : t -> int
- [ ] val consensus_local_state : t -> Consensus.Data.Local_state.t
- [ ] val all_breadcrumbs : t -> Breadcrumb.t list
- [ ] val root_length : t -> int
- [ ] val root : t -> Breadcrumb.t
- [ ] val best_tip : t -> Breadcrumb.t
- [ ] val best_tip_path : ?max_length:int -> t -> Breadcrumb.t list
- [ ] val path_map : ?max_length:int -> t -> Breadcrumb.t -> f:(Breadcrumb.t -> 'a) -> 'a list
- [ ] val hash_path : t -> Breadcrumb.t -> State_hash.t list
- [ ] val find : t -> State_hash.t -> Breadcrumb.t option
- [ ] val find_protocol_state : t -> State_hash.t -> Mina_state.Protocol_state.value option
- [ ] val successor_hashes : t -> State_hash.t -> State_hash.t list
- [ ] val successor_hashes_rec : t -> State_hash.t -> State_hash.t list
- [ ] val successors : t -> Breadcrumb.t -> Breadcrumb.t list
- [ ] val successors_rec : t -> Breadcrumb.t -> Breadcrumb.t list
- [ ] val common_ancestor : t -> Breadcrumb.t -> Breadcrumb.t -> State_hash.t
- [ ] val iter : t -> f:(Breadcrumb.t -> unit) -> unit
- [ ] val best_tip_path_length_exn : t -> int
- [ ] val visualize_to_string : t -> string
- [ ] val visualize : filename:string -> t -> unit
- [ ] val precomputed_values : t -> Precomputed_values.t
- [ ] val genesis_constants : t -> Genesis_constants.t

**Specification reference**

- 

**Other information and links**

https://github.com/MinaProtocol/mina/blob/develop/src/lib/transition_frontier/frontier_base/root_data.mli
https://github.com/MinaProtocol/mina/blob/develop/src/lib/transition_frontier/frontier_base/breadcrumb.mli
https://github.com/MinaProtocol/mina/blob/develop/src/lib/transition_frontier/frontier_base/frontier_intf.ml
