### ISSUE TITLE
Create Full Frontier Traits

### ISSUE THREAD

**Issue by mmacedoeu** [ChainSafe/mina-rs#51]
**Task summary**

WIP task, check if everything is required:

Trait Protocol_states_for_root_scan_state:
- [ ]   val protocol_states_for_next_root_scan_state :
       t
    -> new_scan_state:Staged_ledger.Scan_state.t
    -> old_root_state:(Protocol_state.value, State_hash.t) With_hash.t
    -> (State_hash.t * Protocol_state.value) list

Trait FullFrontier:
- [ ] val create :
     logger:Logger.t
  -> root_data:Root_data.t
  -> root_ledger:Ledger.Any_ledger.witness
  -> consensus_local_state:Consensus.Data.Local_state.t
  -> max_length:int
  -> precomputed_values:Precomputed_values.t
  -> time_controller:Block_time.Controller.t
  -> t
- [ ] val close : loc:string -> t -> unit
- [ ] val root_data : t -> Root_data.t
- [ ] val calculate_diffs : t -> Breadcrumb.t -> Diff.Full.E.t list
- [ ] val protocol_states_for_root_scan_state :   t -> Protocol_states_for_root_scan_state.t
- [ ] val apply_diffs :
     t
  -> Diff.Full.E.t list
  -> enable_epoch_ledger_sync:[`Enabled of Ledger.Db.t | `Disabled]
  -> has_long_catchup_job:bool
  -> [ `New_root_and_diffs_with_mutants of
       Root_identifier.t option * Diff.Full.With_mutant.t list ]

**Specification reference**

- 

**Other information and links**

https://github.com/MinaProtocol/mina/blob/develop/src/lib/transition_frontier/full_frontier/full_frontier.mli
